name = input('请输入姓名:')
com = input('请输入公司:')
title = input('请输入职位:')
phone = input('请输入电话:')
email = input('请输入邮箱:')
print('*'*50)
print(com)
# 空行输出
print()
print('{}({})'.format(name,title))
print()
print('电话:{}'.format(phone))
print('邮箱:{}'.format(email))
print('*'*50)